### PR TITLE
added pre compiled header

### PR DESCRIPTION
**Pull request by Nils75owo**
This helps a lot with compile time when using a compiler which supports this.

On my machine:
Compiletime without this feature:
1:18
Compiletime with this feature:
0:18

### CODE REVIEW

**Comment by drfiemost** [comment]
Haven't tested yet but I see that [target_precompile_headers](https://cmake.org/cmake/help/latest/command/target_precompile_headers.html) has been introduced in cmake 3.16, while we ask for 3.9.
We should either raise the requirement or add a version check.
Also having the README updated with the new option would be good.

**Comment by drfiemost** [comment]
How did you test this? I didn't notice any change, running a clean build using makefiles and gcc 12.

**Comment by Nils75owo** [comment]
Stuff like this makes me want to quit programming...
But now it does seem to work as the build step in the CI checks is now ~20 seconds instead of ~1:20.

**Comment by drfiemost** [comment]
Yep, now I see it, thanks!

**Pull request merged**
